# Generated by Django 3.2 on 2021-04-26 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210425_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
        migrations.AddField(
            model_name='team',
            name='cmnd1',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='cmnd2',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='cmnd3',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='phone1',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='phone2',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='team',
            name='phone3',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')]),
        ),
    ]
