# Generated by Django 3.2 on 2021-04-30 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20210427_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cmnd1',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='cmnd2',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='cmnd3',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{9}|[0-9]{12})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone1',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{10}|[0-9]{11})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone2',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{10}|[0-9]{11})$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone3',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^([0-9]{10}|[0-9]{11})$')]),
        ),
    ]
