# Generated by Django 4.0.4 on 2022-04-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210430_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='school',
        ),
        migrations.AddField(
            model_name='team',
            name='school1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school1', to='register.school'),
        ),
        migrations.AddField(
            model_name='team',
            name='school2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school2', to='register.school'),
        ),
        migrations.AddField(
            model_name='team',
            name='school3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='school3', to='register.school'),
        ),
    ]
