# Generated by Django 4.0.4 on 2022-04-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_remove_team_school_team_school1_team_school2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='school1',
            field=models.ForeignKey(default='Chọn', on_delete=django.db.models.deletion.CASCADE, related_name='school1', to='register.school'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school2',
            field=models.ForeignKey(default='Chọn', on_delete=django.db.models.deletion.CASCADE, related_name='school2', to='register.school'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school3',
            field=models.ForeignKey(default='Chọn', on_delete=django.db.models.deletion.CASCADE, related_name='school3', to='register.school'),
        ),
    ]
